### ISSUE TITLE
커스텀 hook 만들기

### ISSUE THREAD

**Issue by bangsinchur** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#102]
## 설명
compare페이지 내에 hook 만들 코드가 있는지 확인하고,
만들수 있다면 만들어서 적용하기

## TO-DO
- [ ] compare페이지내에 커스텀 hook 가능한 코드 찾기
- [ ] hook만들기
- [ ] 공통 컴포넌트 찾기
- [ ] 페이지 내에 오류혹은 수정할 사항 있는지 찾고 수정하기.
