### ISSUE TITLE
필요 없는 파일 삭제

### ISSUE THREAD

**Issue by shinji530** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#106]
## 설명
더 이상 사용하지 않는 파일 삭제

## TO-DO
- [x] dummy.json 삭제
- [x] mock.js 삭제
- [x] SPagination.js 이름 변경 > Pagination
- [x] Pagination.module.css 삭제, SPagination.module.css 이름 변경
- [x] requestGet api 통일
