### ISSUE TITLE
기업 상세 페이지 - 투자자 리스트 없을시 문구

### ISSUE THREAD

**Issue by GGON123** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#127]
## TO-DO
- [x] 투자자 리스트 없을 시 총액 숨기기 및 문구 설정
- [x] css설정 (미디어쿼리 포함)
- [x] ConvertBillion.js 삭제 및 formatAmount로 수정
