### ISSUE TITLE
비교결과 페이지-투자하기 버튼 하드코딩

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#19]
## 설명
비교 결과 페이지의 투자하기 버튼 실행시 모달창이 나오게 구현
하드코딩이므로 데이터 전송 없이 구현

## TO-DO
- [x] 버튼 클릭시에 모달창이 나오게됨
- [x] 모달창의 확인버튼을 누를시에 모달창이 꺼지면서 팝업창 활성화
- [x] 팝업창 확인버튼이나 X버튼을 누를시에 꺼짐
- [x] 비밀번호입력란 토글버튼 구현
추가 작업사항
- [x] compare-result 페이지 Nav와 겹치는문제 해결
- [x] media 단위를 rem에서 px로 변경
- [x] 브라우저의 창이 작아질 경우에 모달창에 스크롤이 생성됨
- [x] textarea를 사용자가 크기를 임의로 수정하지 못하게 변경
- [x] x 버튼의 이미지를 가운데 정렬
