### ISSUE TITLE
Nav 바 구현

### ISSUE THREAD

**Issue by shinji530** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#2]
## 설명
Nav 컴포넌트 구현

## TO-DO
- [x] 스크롤 내려도 위에 붙어있도록 구현
- [x] 로고 누르면 home으로 이동
- [x] 나의 기업 비교(/compare), 비교 현황(/comare-status), 투자 현황(invest-status) 각각 빈페이지로 이동 (_엔드포인트는 변경될 수 있음_)

## 기타
