### ISSUE TITLE
비교 현황 페이지 생성

### ISSUE THREAD

**Issue by annylee0723** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#20]
## 설명
- api baseURL 주소 추가
- 비교 현황(compare-status) 페이지 생성

## TO-DO
- [x] api.js > baseURL 추가
- [x] page > CompareStatusPage.js 파일 추가
- [x] Main.js > compare-status path 연동

## 기타
CompareStatusPage.js 파일 현재 StartupPage.js와 동일한 코드 변형해서 사용중 -> 추후 수정 예정 입니다
