### ISSUE TITLE
비교 현황 페이지 - 리스트 생성

### ISSUE THREAD

**Issue by annylee0723** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#22]
## 설명
비교 현황 페이지 리스트 생성

## TO-DO
- [x] 리스트 컴포넌트 수정해서 사용
- [x] api로 데이터 받아오기
- [x] api 에러 캐치 메소드 생성
- [x] 페이지네이션 컴포넌트 가져와서 사용

## 기타
리스트 컴포넌트 - 별도의 컴포넌트로 카피해서 수정 후 사용하지만, 추후 지원님 컴포넌트 수정 시 삭제할 예정
