### ISSUE TITLE
비교결과페이지- 비교결과테이블의 데이터구조 변경과 로고이미지 추가, 투자모달창의 기업정보의 목데이터를 받아오는형식으로 변경

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#31]
## 설명
ComparisnTable 컴포넌트의 데이터구조 문자열 -> 숫자 변경, 기업명에 로고이미지 추가
ComparisnTable 컴포넌트의 목데이터를 page에서 받아오도록 변경
InvestmentCompanyBrief 컴포넌트의 목데이터를 page에서 받아오도록 변경

## TO-DO
- [x] ComparisonTable 컴포넌트의 기업명에 로고이미지가 보임
- [x] ComparisonTable 컴포넌트의 데이터 구조가 문자열에서 숫자로 변경
- [x] ComparisonTable 컴포넌트의 목데이터를 page에서 받아오도록 변경
- [x] InvestmentCompanyBrief 컴포넌트의 데이터를 prop으로 받아오게 변경
추가 작업사항
- [x] 글씨 색깔 수정
- [x] 다른 기업 비교하기 버튼에 '/compare'로 가는 링크를 추가했다
