### ISSUE TITLE
비교결과페이지 - sortSelcetor 컴포넌트를 sortContent 컴포넌트로 변경 및 적용

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#57]
## 설명
비교 결과 페이지의 sortSelcetor 컴포넌트를 sortContent 컴포넌트로 변경, 정렬 적용, sortSelector 컴포넌트 삭제

## TO-DO
- [x] sortContent 컴포넌트로 변경되었다
- [x] 정렬이 잘 된다.
- [x] sortSelector 컴포넌트 삭제
- [x] json 파일에서 select 라이브러리 삭제
