### ISSUE TITLE
StartupList컴포넌트

### ISSUE THREAD

**Issue by shinji530** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#6]
## 설명
기업 순위 리스트 컴포넌트 생성

## TO-DO
- [x] 전체 스타트업 목록
- [x] 검색 기능 추가
- [x] 페이지네이션
- [x] dummy data 전송
