### ISSUE TITLE
비교결과페이지 - 나의 기업과 비교할 기업들을 api를 이용해 정보를 받아오게 변경

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#68]
## 설명
비교결과페이지 - 나의 기업과 비교할 기업들을 api를 이용해 정보를 받아오게 변경
나의 기업과 비교할 기업들의 id는 props에서 디폴트값으로 지정해줬습니다.

## TO-DO
- [x] 내가 선택한 기업의 정보가 id를 이용해 정보를 받아와서 보여준다.
- [x] 비교할 기업들의 정보가 id를 이용해 정보를 받아와서 보여준다.
## 추가 작업 사항
- [x] 나의 기업이 다른색으로 표시된다
- [x] 기업 명이 길 경우에 ...으로 생략된다
