### ISSUE TITLE
미디어쿼리,기업비교하기버튼url로 id 전송

### ISSUE THREAD

**Issue by bangsinchur** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#73]
## TO-DO
- [x] 추가 기업비교의 미디어 쿼리 완성하기.
- [x] 기업비교하기 버튼 클릭시, 나의기업Id,비교기업 Id 결과페이지에 url로 전송
- [x] 현재 모달상태 유지까지가능,(선택해제버튼클릭시 compare에 화면에 출력된 데이터 삭제 구현X)
