### ISSUE TITLE
비교결과페이지-나의기업과 비교할 기업을 url에서 받아오고 investment 유효성 검증

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#78]
## 설명
비교결과 페이지의 url에서 나의 기업과 비교할 기업의 id를 받아와 api를 이용해 정보를 받아오고 투자할 때 유효성 검증 받기

## TO-DO
- [x] url에서 받아온 데이터가 잘 적용되었다.
- [x] 나의 기업과 중복되는 비교할 기업들을 필터했다
- [x] 유효성 검증을 통과하지 못하면 버튼을 클릭할 수 없다
- [x] 유효성 검증을 통과하지 못하면 입력란 밑에 안내 문구가 나온다
## 추가 작업 사항
- [x]  비교 결과 페이지 네비게이션 메뉴 활성화 (네비 비교페이지 글씨 불들어오게하기)
