### ISSUE TITLE
비교결과페이지 - 테이블 수정

### ISSUE THREAD

**Issue by taeyeonkim94** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#82]
## 설명
비교결과페이지
1. 테이블의 기업소개란 2줄이상 길어질 경우 ...으로 생략하기
2. 비교하는 개수에 따라 테이블의 크기 달라지게 하기
3. seletor의 크기 조절

## TO-DO
- [x] 기업 소개가 2줄 이상 길어질 경우 ...으로 생략된다
- [x] 비교하는 기업의 숫자에 따라 테이블의 크기가 달라진다
- [x] selector의 크기가 적절하게 변했다.
