### ISSUE TITLE
기업 상세 페이지 - 수정하기 모달 변경

### ISSUE THREAD

**Issue by GGON123** [2-ViewMyStartup-2-FE/2-ViewMyStartup-2team-FE#88]
## TO-DO
- [ ] 수정권한(비밀번호) 인증 모달
- [ ] 인증 실패시 모달 띄우기
- [ ] 수정모달(비밀번호 변경가능)
- [ ] 초기값 입력
- [ ] 수정 실패시 에러 메시지 출력(태연님이 만드신거 갖다 썼습니다)
